<a href="https://colab.research.google.com/github/saipragna25/deep-learning-assignment-2B-/blob/main/DLA2bTensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSORFLOW

In [1]:
import tensorflow as tf


In [2]:
# Scalar vector multiplication

a = tf.random.normal([1])
b = tf.random.normal([2, 3])
c = tf.einsum('k, ij -> ij', a, b)
print(a)
print(b)
print(c)

tf.Tensor([-1.1624095], shape=(1,), dtype=float32)
tf.Tensor(
[[-1.6178854  -0.6592076   1.523907  ]
 [ 0.00492522 -0.462747   -0.43305263]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.8806454   0.7662692  -1.771404  ]
 [-0.00572512  0.5379015   0.50338453]], shape=(2, 3), dtype=float32)


In [4]:
# Vector vector multiplication

a = tf.random.normal([2, 5])
b = tf.random.normal([5, 3])
c = tf.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(c)

tf.Tensor(
[[ 0.60341823  1.6685785  -0.2892078  -1.7653204  -0.28580981]
 [-0.17326589 -1.2343231  -0.08450568 -0.95075023  0.49663165]], shape=(2, 5), dtype=float32)
tf.Tensor(
[[ 0.11722741  0.12966025  1.5570756 ]
 [ 0.22750297  0.200385    0.6265682 ]
 [ 0.8471231   0.29310304  0.36752018]
 [-0.38565868 -0.9017129   0.6479903 ]
 [ 0.44674206  0.1531417   2.6534092 ]], shape=(5, 3), dtype=float32)
tf.Tensor(
[[ 0.75847703  1.8758725  -0.02352458]
 [ 0.21582094  0.6387843  -0.3725431 ]], shape=(2, 3), dtype=float32)


In [5]:
# Outer product

a = tf.range(4)
b = tf.range(3, 6)  
op= tf.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(op)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor(
[[ 0  0  0]
 [ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]], shape=(4, 3), dtype=int32)


In [6]:
# Scalar dot product

a = tf.range(9)
a = tf.reshape(a, [3, 3])

b = tf.range(6)
b = tf.reshape(b, [3, 2])

sp= tf.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(sp)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)
tf.Tensor(204, shape=(), dtype=int32)


In [7]:
# Hadamard product

a = tf.range(8)
a = tf.reshape(a, [2, 4])

b = tf.range(4, 12)
b = tf.reshape(b, [2, 4])

hp = tf.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(hp)

tf.Tensor(
[[0 1 2 3]
 [4 5 6 7]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 4  5  6  7]
 [ 8  9 10 11]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 0  5 12 21]
 [32 45 60 77]], shape=(2, 4), dtype=int32)


In [8]:
# Batch matrix multiplication

a = tf.random.normal([3, 3, 2])
b = tf.random.normal([3, 2, 2])
batch_matrix_mult = tf.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_matrix_mult)

tf.Tensor(
[[[ 0.42498678  2.7804027 ]
  [ 1.6914704  -0.84602237]
  [-0.52680355  1.9482635 ]]

 [[-0.49061704 -0.1871664 ]
  [-1.5978361   0.25197294]
  [ 0.22614114  1.1866479 ]]

 [[-0.25605118  0.1734079 ]
  [ 2.3687525   0.48377344]
  [ 0.27022123  0.1915116 ]]], shape=(3, 3, 2), dtype=float32)
tf.Tensor(
[[[-1.1861887   0.16841118]
  [ 0.6075002  -0.6664281 ]]

 [[-1.3733747   0.5167136 ]
  [ 0.17233083  0.6139628 ]]

 [[-0.16240478  0.3907017 ]
  [-0.8181836  -1.9224372 ]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor(
[[[ 1.1849806  -1.7813659 ]
  [-2.5203617   0.8486756 ]
  [ 1.8084589  -1.3870971 ]]

 [[ 0.6415465  -0.36842173]
  [ 2.2378504  -0.6709217 ]
  [-0.10608052  0.8454079 ]]

 [[-0.10029556 -0.43340543]
  [-0.7805122  -0.00454837]
  [-0.20057687 -0.26259315]]], shape=(3, 3, 2), dtype=float32)


In [9]:
# Tensor reduction

a = tf.random.normal([2, 3, 5, 7])
b = tf.random.normal([4, 1, 3, 11, 5])
tensor_reduction = tf.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, tensor_reduction.shape)

(2, 3, 5, 7) (4, 1, 3, 11, 5) (2, 7, 4, 1, 11)


In [10]:
# Transpose

a = tf.range(8)
a = tf.reshape(a, [4, 2])
transpose = tf.einsum('ij -> ji', a)
print(a)
print(transpose)

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]
 [6 7]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[0 2 4 6]
 [1 3 5 7]], shape=(2, 4), dtype=int32)


In [11]:
# Bilinear transformation

a = tf.random.normal([2, 3])
b = tf.random.normal([3, 3, 4])
c = tf.random.normal([2, 4])
bilinear_transform = tf.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear_transform)

tf.Tensor(
[[-0.6954806  -1.0824219   0.19930811]
 [ 0.4508692   0.4881065   1.4258547 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[ 1.0065144  -2.2945285   0.4335356  -0.63619435]
  [-0.1890557   0.3767921  -1.5309983  -0.07226737]
  [-1.4231861  -0.06285733 -0.21785803 -1.4176905 ]]

 [[ 0.6462956  -1.1730558   1.2180301  -0.2377255 ]
  [-0.33302912  0.5950922   0.01317004  0.4761292 ]
  [ 0.18212163  0.9193005   1.000511   -1.0902238 ]]

 [[-1.4421568  -0.3345002   1.4541928  -0.45049998]
  [ 0.03094517 -0.14419581  0.05774543 -0.42188388]
  [ 0.4740459  -0.20740335 -0.6087009   0.6669906 ]]], shape=(3, 3, 4), dtype=float32)
tf.Tensor(
[[ 0.32929042 -1.9315276  -0.50193876 -1.3795474 ]
 [-0.3145737   0.9259973   1.050156   -0.9860585 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-3.514067    0.41202655 -0.9663125 ]
 [ 1.0591105   4.361745   -1.2192565 ]], shape=(2, 3), dtype=float32)


In [12]:
# Attention

# Parameters
# [hidden_dimension]
bM = tf.random.normal([7])
br = tf.random.normal([7]) 
w = tf.random.normal([7])
# [hidden_dimension x hidden_dimension]
WY = tf.random.normal([7, 7])
Wh = tf.random.normal([7, 7])
Wr = tf.random.normal([7, 7])
Wt = tf.random.normal([7, 7])

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = tf.einsum('ik, kl -> il', ht, Wh) + tf.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = tf.expand_dims(tmp, 1)
  tmp_tiled = tf.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = tf.tanh(tf.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bM)
  
  # [batch_size x sequence_length]
  at = tf.nn.softmax(tf.einsum('ijk, k -> ij', Mt, w)) 
  
  # [batch_size x hidden_dimension]
  rt = tf.einsum('ijk, ij -> ik', Y, at) + tf.tanh(tf.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = tf.random.normal([3,5,7])
# [batch_size x hidden_dimension]
ht = tf.random.normal([3, 7])
rt1 = tf.random.normal([3, 7])

rt, at = attention(Y, ht, rt1)

print(at)

tf.Tensor(
[[1.64319366e-01 6.23683259e-02 6.27312809e-02 6.47128642e-01
  6.34524003e-02]
 [1.55577045e-02 6.80592060e-01 2.01225936e-01 8.85632485e-02
  1.40611008e-02]
 [5.44860261e-04 2.09528938e-04 1.02063246e-01 7.98429549e-03
  8.89198005e-01]], shape=(3, 5), dtype=float32)


In [13]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return tf.expand_dims(zl, 1) + tf.tanh(tf.einsum('bk, aki -> bai', zl, W) + b)

# Inputs - [batch_size x hidden_dimension]
zl = tf.random.normal([2, 3])
# Parameters - [num_actions x hidden_dimension]
b = tf.random.normal([5, 3])
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = tf.random.normal([5, 3, 3])

transition(zl)

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[ 0.2714504 ,  1.0510089 ,  0.7371785 ],
        [ 1.4759377 ,  1.6823572 ,  0.77424926],
        [ 2.1360867 ,  1.6881757 ,  0.56467247],
        [ 0.2662291 ,  0.09769791,  0.77615154],
        [ 0.29988843,  1.6840495 , -0.8147847 ]],

       [[-1.2604777 ,  1.0766848 ,  1.0638258 ],
        [ 0.20449924,  1.1590903 ,  0.65969783],
        [ 0.19153205,  0.67433715,  1.1238798 ],
        [-1.266081  ,  0.8745402 , -0.22465064],
        [-0.40437126,  1.1931056 ,  0.90246016]]], dtype=float32)>