<a href="https://colab.research.google.com/github/saipragna25/deep-learning-assignment-2B-/blob/main/DLA2bNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [1]:
import numpy as np

In [2]:
# Scalar vector multiplication

a = np.array([5])
b = np.array([4, 7, 6, 8])
c = np.einsum('i, i -> i', a, b)
print(a)
print(b)
print(c)

[5]
[4 7 6 8]
[20 35 30 40]


In [3]:
# Vector vector multiplication

a = np.random.randn(5, 8)
b = np.random.randn(8, 4)
c = np.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(c)

[[ 0.11758502 -0.83939882  0.4014455   0.2024525  -0.76629728 -0.63077949
   0.15361533  0.55781273]
 [-2.06324322  1.63712883  0.76455973  3.04716907  1.30972268 -0.96819733
   0.35150093 -1.27102686]
 [ 1.25383626 -1.78100693 -0.22731336 -0.73130693  0.92294403  0.24027915
  -0.6419564   0.47934183]
 [-1.24236545  1.27189565 -0.27399734 -0.6800829  -1.21754787  0.08075385
  -1.34535684 -0.09597031]
 [ 1.03574621 -1.36274281  0.4393597   0.25347263 -0.08911126 -0.51806398
   0.23982865  0.97738324]]
[[ 1.65954539 -0.42824479 -0.1692948  -0.78438275]
 [ 1.58333028  0.19950346 -0.8776605   1.76589518]
 [-0.19440198 -1.71677109 -0.78718628 -0.67532792]
 [ 0.3794075  -0.88053243  1.25821931 -0.21370678]
 [ 0.42950953 -0.64945234 -1.03876731 -1.05780566]
 [ 0.5870304   0.80460016 -0.67154408  0.10780458]
 [ 1.02940373 -0.13357065 -0.81093682  0.06549848]
 [ 1.45562692 -0.9504807   1.52490072  2.02794976]]
[[-0.86445701 -1.64583461  2.60115541 -0.00502439]
 [-1.31857068 -3.25399711 -0.78893

In [4]:
# Outer product

a = np.arange(2, 5)
b = np.arange(4, 7)  
op = np.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(op)

[2 3 4]
[4 5 6]
[[ 8 10 12]
 [12 15 18]
 [16 20 24]]


In [5]:
# Scalar dot product

a = np.arange(9).reshape(3, 3)
b = np.arange(6).reshape(3, 2)
sd = np.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(sd)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]]
204


In [6]:
# Hadamard product

a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)
hp = np.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(hp)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  7 16]
 [27 40 55]]


In [7]:
# Batch matrix multiplication

a = np.random.randn(3, 3, 2)
b = np.random.randn(3, 2, 2)
batch_matrix_mul = np.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_matrix_mul)

[[[ 0.3660221   1.16746191]
  [ 0.64007015  0.76661596]
  [ 0.6362116  -1.51477969]]

 [[ 0.43188904 -1.88776141]
  [-0.82670685 -1.32794853]
  [-0.49204884 -2.177318  ]]

 [[-1.75830366 -0.5881517 ]
  [-0.2595577   0.24517038]
  [ 1.19503348 -1.864766  ]]]
[[[-1.43382497 -0.31511392]
  [-0.59181921 -0.11593465]]

 [[ 0.01339535  0.81841116]
  [ 1.0712573   0.4308367 ]]

 [[-0.38577912 -0.59837473]
  [ 0.69396116  0.75084708]]]
[[[-1.215738   -0.25068794]
  [-1.37144661 -0.29057236]
  [-0.01574037 -0.02486368]]

 [[-2.01649289 -0.45985408]
  [-1.43364858 -1.24871506]
  [-2.33905896 -1.34076675]]

 [[ 0.2701624   0.61051248]
  [ 0.27027066  0.33939823]
  [-1.75509415 -2.11523193]]]


In [8]:
# Tensor reduction

a = np.random.randn(2, 3, 5, 7)
b = np.random.randn(4, 1, 3, 11, 5)
tensor_reduction = np.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, tensor_reduction.shape)

(2, 3, 5, 7) (4, 1, 3, 11, 5) (2, 7, 4, 1, 11)


In [9]:
# Transpose

a = np.arange(6).reshape(2, 3)
transpose = np.einsum('ij -> ji', a)
print(a)
print(transpose)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [10]:
# Bilinear transformation

a = np.random.randn(2, 3)
b = np.random.randn(3, 3, 4)
c = np.random.randn(2, 4)
bilinear_transform = np.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear_transform)

[[ 1.10294739 -0.15737974  2.13059427]
 [-0.68971427  1.12839421  0.14268645]]
[[[-0.20549254 -0.88648725 -1.82254038 -1.18369266]
  [-0.27143815 -0.52203765 -0.97402936 -1.49241793]
  [ 0.24705912 -0.47481361 -0.00589876 -0.98482658]]

 [[ 0.60659412 -1.74238307 -0.18101148 -1.30691094]
  [ 0.60281994 -1.06015815 -2.0657196  -0.07606493]
  [ 1.23250454 -0.88085221 -1.43373865 -0.74542282]]

 [[-0.33660595 -0.76032103  0.73089189  1.25098827]
  [ 0.37501483  0.19332223  2.59418736 -1.35725301]
  [ 2.11740711  0.8143601  -1.36110312 -0.33155631]]]
[[ 1.46010389  0.01349315  0.24658769 -0.50926541]
 [-0.78902583 -1.86462563  0.06341826  0.61092944]]
[[ 1.62713455  5.43800895  4.90176575]
 [-0.41928111  0.15918919 -3.70701374]]


In [11]:
# Attention

# Parameters
# [hidden_dimension]
bm = np.random.randn(7)
br = np.random.randn(7) 
w = np.random.randn(7)
# [hidden_dimension x hidden_dimension]
WY = np.random.randn(7, 7)
Wh = np.random.randn(7, 7)
Wr = np.random.randn(7, 7)
Wt = np.random.randn(7, 7)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = np.einsum('ik, kl -> il', ht, Wh) + np.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = np.expand_dims(tmp, 1)
  tmp_tiled = np.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = np.tanh(np.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bm)
  
  # [batch_size x sequence_length]
  at = np.einsum('ijk, k -> ij', Mt, w)
  at = np.exp(at)/np.sum(np.exp(at))
  
  # [batch_size x hidden_dimension]
  rt = np.einsum('ijk, ij -> ik', Y, at) + np.tanh(np.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = np.random.randn(3,5,7)
# [batch_size x hidden_dimension]
ht = np.random.randn(3, 7)
rt1 = np.random.randn(3, 7)

rt, at = attention(Y, ht, rt1)

print(at)

[[0.03357665 0.01150208 0.00280826 0.0040188  0.03702644]
 [0.10210131 0.1395247  0.15248223 0.24607468 0.2499145 ]
 [0.01303337 0.00400078 0.00146563 0.00043518 0.00203538]]


In [12]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return np.expand_dims(zl, 1) + np.tanh(np.einsum('bk, aki -> bai', zl, W) + b)

# Inputs - [batch_size x hidden_dimension]
zl = np.random.rand(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = np.random.rand(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = np.random.rand(5, 3, 3)

transition(zl)

array([[[1.89538956, 1.30033334, 1.62667387],
        [1.87882896, 1.61962213, 1.49625184],
        [1.78359614, 1.66217099, 1.64809212],
        [1.44683975, 1.5938915 , 1.50915968],
        [1.92048609, 1.62395541, 1.57652446]],

       [[1.49114789, 0.68021832, 0.96546328],
        [1.45949992, 0.98625242, 0.86208566],
        [1.27719473, 1.05514509, 1.11672489],
        [0.93946149, 0.99054312, 0.97190754],
        [1.58477788, 1.06963105, 0.87262261]]])