<a href="https://colab.research.google.com/github/saipragna25/deep-learning-assignment-2B-/blob/main/DLA2bPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PYTORCH


In [2]:
import torch


In [3]:
# Scalar vector multiplication

a = torch.rand(1)
b = torch.rand(4, 6)
c = torch.einsum('i, ij -> ij', [a, b])
print(a)
print(b)
print(c)

tensor([0.7342])
tensor([[0.3294, 0.2023, 0.0293, 0.7053, 0.0873, 0.5140],
        [0.9745, 0.2776, 0.2000, 0.8226, 0.2266, 0.8492],
        [0.5204, 0.6569, 0.0837, 0.6028, 0.5085, 0.1036],
        [0.9294, 0.9356, 0.4526, 0.3326, 0.1977, 0.8051]])
tensor([[0.2419, 0.1485, 0.0215, 0.5179, 0.0641, 0.3774],
        [0.7155, 0.2038, 0.1468, 0.6040, 0.1664, 0.6235],
        [0.3821, 0.4823, 0.0615, 0.4426, 0.3734, 0.0760],
        [0.6824, 0.6869, 0.3323, 0.2442, 0.1451, 0.5911]])


In [4]:
# Vector vector multiplication

a = torch.rand(2, 4)
b = torch.rand(4, 6)
c= torch.einsum('ij, jk -> ik', [a, b])
print(a)
print(b)
print(c)

tensor([[0.5318, 0.8626, 0.3874, 0.1230],
        [0.0476, 0.1583, 0.8002, 0.9898]])
tensor([[0.6362, 0.5842, 0.1136, 0.1367, 0.0992, 0.6324],
        [0.7461, 0.6953, 0.7746, 0.5065, 0.8117, 0.9511],
        [0.4874, 0.9649, 0.1934, 0.1719, 0.8082, 0.0674],
        [0.2992, 0.0246, 0.3222, 0.9294, 0.1101, 0.9374]])
tensor([[1.2075, 1.2873, 0.8431, 0.6905, 1.0795, 1.2981],
        [0.8345, 0.9343, 0.6018, 1.1442, 0.8889, 1.1624]])


In [5]:
# Outer product

a = torch.arange(5)
b = torch.arange(3, 6)  
op= torch.einsum('i,j -> ij', [a, b])
print(a)
print(b)
print(op)

tensor([0, 1, 2, 3, 4])
tensor([3, 4, 5])
tensor([[ 0,  0,  0],
        [ 3,  4,  5],
        [ 6,  8, 10],
        [ 9, 12, 15],
        [12, 16, 20]])


In [6]:
# Scalar dot product

a = torch.arange(9).reshape(3, 3)
b = torch.arange(6).reshape(3, 2)
sp = torch.einsum('ij, jk ->', [a, b])
print(a)
print(b)
print(sp)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor(204)


In [7]:
# Hadamard product

a = torch.arange(8).reshape(2, 4)
b = torch.arange(4, 12).reshape(2, 4)
hp = torch.einsum('ij, ij -> ij', [a, b])
print(a)
print(b)
print(hp)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  5, 12, 21],
        [32, 45, 60, 77]])


In [8]:
# Batch matrix multiplication

a = torch.randn(3, 3, 5)
b = torch.randn(3, 5, 2)
batch_matrix_mul = torch.einsum('bij, bjk -> bik', [a, b])
print(a)
print(b)
print(batch_matrix_mul)

tensor([[[-2.5184,  0.8463, -0.1660, -0.7315, -0.8490],
         [ 1.4984,  1.0025,  1.6241, -0.4707, -0.8756],
         [ 0.0591, -1.3159, -0.1089, -1.2147,  1.2578]],

        [[ 0.8064,  0.9094, -0.0124,  2.4760, -1.5924],
         [-0.9544,  1.2134, -0.1827,  0.3308,  0.2178],
         [-0.6285,  0.7844, -0.5178,  2.2740, -0.2897]],

        [[ 1.3131, -0.3015, -0.8730,  1.6285, -1.4950],
         [ 1.1432,  1.0117, -1.3117,  0.3460,  0.0261],
         [-1.8562,  0.6623, -0.6490, -0.0235,  1.1036]]])
tensor([[[ 1.1617, -0.0744],
         [-1.0282,  0.7458],
         [ 0.1351,  0.4993],
         [-0.1549, -0.7520],
         [-0.7117, -0.6169]],

        [[-1.0381, -0.8409],
         [ 0.0165,  0.7990],
         [ 0.2251, -0.0251],
         [ 0.5351,  0.8074],
         [ 0.3985,  0.4352]],

        [[-0.6814,  1.0494],
         [-0.1585,  2.1327],
         [-0.7298,  0.2824],
         [ 0.3727, -0.6336],
         [-0.8802, -2.5468]]])
tensor([[[-3.1007,  1.8095],
         [ 1.6256,  

In [9]:
# Tensor reduction

a = torch.randn(2, 3, 5, 7)
b = torch.randn(4, 1, 3, 11, 5)
tensor_reduction = torch.einsum('pqrs, tuqvr -> pstuv', [a, b])
print(a.shape, b.shape, tensor_reduction.shape)

torch.Size([2, 3, 5, 7]) torch.Size([4, 1, 3, 11, 5]) torch.Size([2, 7, 4, 1, 11])


In [10]:
# Transpose

a = torch.arange(8).reshape(4, 2)
transpose = torch.einsum('ij -> ji', [a])
print(a)
print(transpose)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
tensor([[0, 2, 4, 6],
        [1, 3, 5, 7]])


In [13]:
# Bilinear transformation

a = torch.randn(2, 3)
b = torch.randn(3, 3, 4)
c = torch.randn(2, 4)
bilinear_transform = torch.einsum('ik, jkl, il -> ij', [a, b, c])
print(a)
print(b)
print(c)
print(bilinear_transform)

tensor([[-0.2455, -0.3778,  1.5716],
        [-1.1057,  0.9032,  0.5375]])
tensor([[[-1.3603,  0.4806, -2.1497,  1.9873],
         [-0.4892,  2.2299,  2.0188, -1.6711],
         [ 0.6978,  2.4299,  0.0644, -0.8094]],

        [[ 0.2159, -1.2592, -0.1304, -1.0520],
         [-1.3401,  0.3318, -1.9800, -1.6966],
         [-0.7593, -1.9865,  0.7129, -0.0871]],

        [[-1.0283,  0.2825,  0.0713,  0.5208],
         [-0.3179,  0.4338,  0.4392, -1.7319],
         [-0.5855, -0.5687, -0.6299,  0.8627]]])
tensor([[ 0.9253, -0.6718, -1.6440, -0.8909],
        [-0.6574,  1.1717, -0.7898, -0.8136]])
tensor([[ 0.7999, -2.5143,  0.5026],
        [ 2.3476,  3.2867,  0.7634]])


In [14]:
# Attention

def random_tensors(shape, num=1, requires_grad=False):
  tensors = [torch.randn(shape, requires_grad=requires_grad) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors

# Parameters
# [hidden_dimension]
bM, br, w = random_tensors([7], num=3, requires_grad=True)
# [hidden_dimension x hidden_dimension]
WY, Wh, Wr, Wt = random_tensors([7, 7], num=4, requires_grad=True)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = torch.einsum('ik, kl -> il', [ht, Wh]) + torch.einsum('ik, kl -> il', [rt1, Wr])

  Mt = torch.tanh(torch.einsum('ijk, kl -> ijl', [Y, WY]) + tmp.unsqueeze(1).expand_as(Y) + bM)
  
  # [batch_size x sequence_length]
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w])) 
  
  # [batch_size x hidden_dimension]
  rt = torch.einsum('ijk, ij -> ik', [Y, at]) + torch.tanh(torch.einsum('ij, jk -> ik', [rt1, Wt]) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = torch.randn(3,5,7)
# [batch_size x hidden_dimension]
ht, rt1 = random_tensors([3, 7], num=2)

rt, at = attention(Y, ht, rt1)

print(at)

tensor([[0.0647, 0.2903, 0.2387, 0.1789, 0.2274],
        [0.2058, 0.2523, 0.1002, 0.3406, 0.1010],
        [0.2283, 0.1497, 0.1871, 0.2983, 0.1366]], grad_fn=<SoftmaxBackward0>)


<ipython-input-14-0f495568e4dc>:20: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w]))


In [15]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return zl.unsqueeze(1) + torch.tanh(torch.einsum('bk, aki -> bai', [zl, W]) + b)

# Inputs - [batch_size x hidden_dimension]
zl = torch.randn(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = torch.randn(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = torch.randn(5, 3, 3)

transition(zl)

tensor([[[ 1.1293, -2.3820,  2.1949],
         [ 0.0228, -0.7951,  2.3060],
         [ 1.0738, -0.5156,  0.3137],
         [-0.7932, -2.3968,  2.2596],
         [ 1.1106, -0.4044,  2.3088]],

        [[ 0.0533,  0.2774,  0.0065],
         [-0.6033, -0.3555,  0.2179],
         [ 0.7827, -0.5702,  0.2113],
         [ 0.7182, -0.3978,  0.3556],
         [-0.1743, -0.0963, -0.2351]]])